// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wirwnewayxawtftwyqnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpcnduZXdheXhhd3RmdHd5cW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNDgyOTMsImV4cCI6MjA1NjcyNDI5M30.QQvzxZjXfDbhXzIaBAyQgFDoCeaDCNRMaRJljLOroeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);